name: frontend
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Supabase + env
  supabase_flutter: ^2.6.0
  flutter_dotenv: ^5.1.0

  # existing
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  image_picker: ^1.0.7
  camera: ^0.10.5+5
  camera_web: ^0.3.2+4
  google_maps_flutter: ^2.6.1
  flutter_tts: ^4.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # logo splash
    - assets/logo.png

    # env
    - .env

  fonts:
    - family: "Tilt Warp"
      fonts:
        - asset: assets/TiltWarp-Bold.ttf
          weight: 700

    - family: "Comfortaa"
      fonts:
        - asset: assets/Comfortaa-Regular.ttf
          weight: 400
